using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

// To do Validation
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace SJGH_Project.Models
{
    [MetadataType(typeof(NewsFeedValidation))]
    public partial class NeewFeed
    { 
        // Empty: name of the class matches name of table
    }

    [Bind(Exclude="news_id")]
    public partial class NewsFeedValidation
    {   
        //title validation
        [DisplayName("News Title *")]
        [Required(ErrorMessage = "Please enter a title")]
        [StringLength(50, ErrorMessage = "Please enter between 2 and 50 characters", MinimumLength = 2)]
        public string headline { get; set; }

        // CONTENT OF NEWS
        [DisplayName("News Body *")]
        [Required(ErrorMessage = "Please enter the article ")]
        [AllowHtml] // allows the HTML GENERATED BY CKEDITOR
        public string body { get; set; }

        //DATE
        [DataType(DataType.DateTime)]
        [DisplayName("Publication Date - mm/dd/yyyy")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime date { get; set; }

        // AUTHOR
        [DisplayName("Author (SJGH is default)")]
        public string author { get; set; }

        // Published
        [DisplayName("Want to publish it?")]
        public string published { get; set; }

        //IMAGE
        [DisplayName("Upload a featured image (604 X 302 recommended)")]
        public string photo_url { get; set; }

        //Category
        [DisplayName("Set as featured or regular news *")]
        [Required(ErrorMessage = "Please select and option")]
        public string category { get; set; }
    }
}